let counter = 0;
export const nerd = () => {
  if (counter < 1) {
    console.log(
      "                            .ss$$$$$$$$$$$$$$$ss.\r\n                       .s$$$$$$$$$$$$$$$$$$$$$$$$$$ss.\r\n                   .s$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$s\r\n                 .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$.\r\n               .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$s\r\n             .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$s.\r\n            $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\r\n          .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\r\n          $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\r\n        .$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\r\n        $$$$$$$$$$$$$$$$$$$$                                  $$\r\n        $$$$$$$$$$$$$$$$$$     .\r\n       s$$$$$$$$$$$$$$$$$     sssss.                           s\r\n      ss $$$$$$$$$$$$$$$          ssss                      ss$s\r\n     sss   $$$$$$$$$$$            ssss$$$$ss              $$$$s.\r\n    sssss   $$$$$$$$   s.      .sss$$$$$$$$sss      sss$$$$$$s\r\n    ss$ssss  $$$$$$$  sss.  .ss$$$$$$ss$ss     .         s$$$$s.\r\n    ss$s   s  $$$$$$ ss.ss           ..        ss           .sss\r\n     ss   s $s $$$$$ ss..s.                   ss\r\n      s ss$$$$s $$$$ ssssss.                 .ss\r\n    ss     s$$$s $$$ ssssssssss..           ssss.              .\r\n    ss      $$  s $$ ss..ss$$$$sss        .sssss              ..\r\n     s      s$$ss  $ ssss.sss$$$sss       .sssss.     ss..\r\n      s.     $     $ .sss . .ss$sss        .  sssssss...   ss$\r\n        ss   sssss$$ ..ss   ...sssss            .sss.       s\r\n          ss    $$ $ .ss..s .sssssss\r\n            ss$$  $$  .ssssss .sssss              ..       $\r\n                $$$$  .ss$$ssss...s.s        ..sss$$ssss.\r\n               $$.$$$  .ss$$sss.. sss.    .ssss$$s..s$ss. s\r\n               ss ssss  .sssssss...sss.      .ssss$$ss..  .\r\n               ss  ssss   .ssssssss.sss.        .sss.\r\n               ss    .ssss    .sssssssss.               s\r\n               ss      .sssss.  .sssssss.s .. ..ss$s. .s\r\n              ss         sssssss.  .sssssssssssss$$s. .ss\r\n            $ss           ssssssss.   ..sssssssssss  .ss.\r\n          $$$$.            .sssssssss.     ssssss ssss.$s\r\n      s$$$$$$$$s.             ..ssssssssss......ssss. s$$$s\r\n    .s$$$$$$$$$$$s.              .ssssssssssssssss. s$$$$$ss.\r\n       s$$$$$$$$$$$$$$ss..          .ssssssssss. .s$$$$$$$$s\r\n         s$$$$$$$$$$$$$$$$$$$ssss...   ...ss.. s$$$$$$$$$s\r\n           s$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$s\r\n              .s$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$s\r\n                    .s$$$$$$$$$$$$$$$$$$$$$$$$$$$$$s\r\n                          .s$$$$$$$$$$$$$$$$$$$$s\r\n                                ..s$$$$$$$$$$s\r\n\r\n\r\nL\u00F3gico, otro nerd.🖖"
    );
    counter++;
  }
};
