import Sequelize from "./sequelize.svg";
import Yarn from "./yarn.svg";
import Webpack from "./webpack.svg";
import Typescript from "./typescript.svg";
import ReactSVG from "./react.svg";
import PostgreSql from "./Postgres.svg";
import Npm from "./npm.svg";
import Node from "./Node.svg";
import Next from "./next.svg";
import Linux from "./linux.svg";
import Javascript from "./javascript.svg";
import Html from "./html.svg";
import Heroku from "./heroku.svg";
import Express from "./express.svg";
import Css from "./css.svg";
import Git from "./Git.svg";
import Code from "./code.svg";
import Cross from "./cross.svg";
import Discord from "./discord.svg";
import Firebase from "./Firebase.svg";
import Github from "./Github.svg";
import GithubSmall from "./GithubSmall.svg";
import Linkedin from "./linkedin.svg";
import Mail from "./mail.svg";
import Schedule from "./schedule.svg";
import SwipLeft from "./swip_left.svg";
import SwipRight from "./swip_right.svg";
import Terminal from "./terminal.svg";
import Web from "./web.svg";
import Python from "./Python.svg";
import Menu from "./menu.svg";

export const SequelizeIcon = () => <Sequelize />;
export const YarnIcon = () => <Yarn />;
export const WebpackIcon = () => <Webpack />;
export const TypescriptIcon = () => <Typescript />;
export const ReactIcon = () => <ReactSVG />;
export const PostgreSqlIcon = () => <PostgreSql />;
export const NpmIcon = () => <Npm />;
export const NodeIcon = () => <Node />;
export const NextIcon = () => <Next />;
export const LinuxIcon = () => <Linux />;
export const JavascriptIcon = () => <Javascript />;
export const HtmlIcon = () => <Html />;
export const HerokuIcon = () => <Heroku />;
export const ExpressIcon = () => <Express />;
export const CssIcon = () => <Css />;
export const GitIcon = () => <Git />;
export const CodeIcon = () => <Code />;
export const CrossIcon = () => <Cross />;
export const DiscordIcon = () => <Discord />;
export const FirebaseIcon = () => <Firebase />;
export const GithubIcon = (props: { small?: boolean; large?: boolean }) =>
  props.small ? <GithubSmall /> : <Github />;
export const LinkedinIcon = () => <Linkedin />;
export const MailIcon = () => <Mail />;
export const ScheduleIcon = () => <Schedule />;
export const SwipLeftIcon = () => <SwipLeft />;
export const SwipRightIcon = () => <SwipRight />;
export const TerminalIcon = () => <Terminal />;
export const WebIcon = () => <Web />;
export const PythonIcon = () => <Python />;
export const MenuIcon = () => <Menu />;
